// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"
)

type PendingCard struct {
	ID           int64
	LanguageCode string
	Token        string
	SourceImage  []byte
	Meta         json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ExportedAt   sql.NullTime
}

type Text struct {
	ID           int64
	LanguageCode string
	Content      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
